### ISSUE TITLE
Update to 1.20.6

### ISSUE THREAD

**Issue by Wamens** [CodedRed-Spigot/PlayTimes#58]
Can you please add support for 1.20.6?

**Comment by Kaerix** [comment]
@CodedRedGIT

**Comment by Goinging** [comment]
Yeah every few paper dev builds this plugin works again, then doesn't for some reason.

**Comment by t4ba** [comment]
yeah man please update it to new version

**Comment by Goinging** [comment]
Btw for people looking in here if you downgrade paper versions to around version ~134ish this plugin works perfectly fine. I haven't tested all versions so I am not sure which build breaks it, but 134 should work. Paper is pretty stable right now so it is not super necessary to always be on the newest version anyway, however, this is only a temporary solution.

**Comment by t4ba** [comment]
CodedRed was last seen: 7w 2d ago

**Comment by t4ba** [comment]
> Can you please add support for 1.20.6?

use this for now

[PlayTimes-1.6.1.jar.zip](https://github.com/user-attachments/files/15857210/PlayTimes-1.6.1.jar.zip)

**Comment by CodedRedGIT** [comment]
https://github.com/CodedRed-Spigot/PlayTimes/releases/tag/v1.6.2

Production Release Soon. ETA Tomorrow Night ~ 8pm CDT

**Comment by CodedRedGIT** [comment]
https://www.spigotmc.org/resources/playtimes-track-player-playtime.58858/update?update=549074

Update posted. Please make another ticket if you are experiencing anymore issues. I promise to be much faster in support! Sorry for the few weeks off been busy with IRL.

**Comment by CodedRedGIT** [comment]
https://www.spigotmc.org/resources/playtimes-track-player-playtime.58858/update?update=549204

**Comment by t4ba** [comment]
getting this error when running /playtime for offline players 

23.06 11:38:40 [Server] WARN [Playtimes] Plugin Playtimes v1.6.2b generated an exception while executing task 1364399
23.06 11:38:40 [Server] INFO java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because the return value of "org.bukkit.OfflinePlayer.getName()" is null
23.06 11:38:40 [Server] INFO at PlayTimes-1.6.2b.jar/me.codedred.playtimes.server.ServerOffline.getUUID(ServerOffline.java:32) ~[PlayTimes-1.6.2b.jar:?]
23.06 11:38:40 [Server] INFO at PlayTimes-1.6.2b.jar/me.codedred.playtimes.server.ServerManager.getUUID(ServerManager.java:39) ~[PlayTimes-1.6.2b.jar:?]
23.06 11:38:40 [Server] INFO at PlayTimes-1.6.2b.jar/me.codedred.playtimes.commands.Time$2.run(Time.java:292) ~[PlayTimes-1.6.2b.jar:?]
23.06 11:38:40 [Server] INFO at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
23.06 11:38:40 [Server] INFO at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
23.06 11:38:40 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.20.6.jar:?]
23.06 11:38:40 [Server] INFO at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
23.06 11:38:40 [Server] INFO at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
23.06 11:38:40 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by t4ba** [comment]
playtimes version : 1.6.2b
server version : Server version: 1.20.6-2233-0d6766e (MC: 1.20.6)
